<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\RangeRequest;

/**
 * @api
 */
enum SortOrder: int
{
    /** default, no sorting */
    case NONE = 0;

    /** lowest target value first */
    case ASCEND = 1;

    /** highest target value first */
    case DESCEND = 2;
}
