<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\RangeRequest;

/**
 * @api
 */
enum SortTarget: int
{
    case KEY = 0;
    case VERSION = 1;
    case CREATE = 2;
    case MOD = 3;
    case VALUE = 4;
}
