<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto
 */

declare(strict_types=1);

namespace V3lockpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LockRequest
{
    /**
     * @param string $name name is the identifier for the distributed shared lock to be acquired.
     * @param int $lease lease is the ID of the lease that will be attached to ownership of the
     * lock. If the lease expires or is revoked and currently holds the lock,
     * the lock is automatically released. Calls to Lock with the same lease will
     * be treated as a single acquisition; locking twice with the same lease is a
     * no-op.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $name = '',
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public int $lease = 0,
    ) {}
}
