<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto
 */

declare(strict_types=1);

namespace V3lockpb;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 *
 * The lock service exposes client-side locking facilities as a gRPC interface.
 */
final readonly class LockClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * Lock acquires a distributed shared lock on a given named lock.
     * On success, it will return a unique key that exists so long as the
     * lock is held by the caller. This key can be used in conjunction with
     * transactions to safely ensure updates to etcd only occur while holding
     * lock ownership. The lock is held until Unlock is called on the key or the
     * lease associate with the owner expires.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function lock(
        \V3lockpb\LockRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \V3lockpb\LockResponse {
        /** @var Client\Invoke<\V3lockpb\LockRequest, \V3lockpb\LockResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/v3lockpb.Lock/Lock',
            output: \V3lockpb\LockResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Unlock takes a key returned by Lock and releases the hold on lock. The
     * next Lock caller waiting for the lock will then be woken up and given
     * ownership of the lock.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function unlock(
        \V3lockpb\UnlockRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \V3lockpb\UnlockResponse {
        /** @var Client\Invoke<\V3lockpb\UnlockRequest, \V3lockpb\UnlockResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/v3lockpb.Lock/Unlock',
            output: \V3lockpb\UnlockResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
