<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto
 */

declare(strict_types=1);

namespace V3lockpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LockResponse
{
    /**
     * @param string $key key is a key that will exist on etcd for the duration that the Lock caller
     * owns the lock. Users should not modify this key or the lock may exhibit
     * undefined behavior.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\BytesT::T)]
        public string $key = '',
    ) {}
}
