<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto
 */

declare(strict_types=1);

namespace V3lockpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class UnlockRequest
{
    /**
     * @param string $key key is the lock ownership key granted by Lock.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $key = '',
    ) {}
}
