<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto
 */

declare(strict_types=1);

namespace V3lockpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class UnlockResponse
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
    ) {}
}
