<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

/**
 * @api
 */
enum AlarmType: int
{
    /** default, used to query if any alarm is active */
    case NONE = 0;

    /** space quota is exhausted */
    case NOSPACE = 1;

    /** kv store corruption detected */
    case CORRUPT = 2;
}
