<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class AlarmRequest
{
    /**
     * @param \Etcdserverpb\AlarmRequest\AlarmAction $action action is the kind of alarm request to issue. The action
     * may GET alarm statuses, ACTIVATE an alarm, or DEACTIVATE a
     * raised alarm.
     * @param \BcMath\Number $memberID memberID is the ID of the member associated with the alarm. If memberID is 0, the
     * alarm request covers all members.
     * @param \Etcdserverpb\AlarmType $alarm alarm is the type of alarm to consider for this request.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Etcdserverpb\AlarmRequest\AlarmAction::class))]
        public \Etcdserverpb\AlarmRequest\AlarmAction $action = \Etcdserverpb\AlarmRequest\AlarmAction::GET,
        #[Reflection\Field(2, Reflection\Uint64T::T)]
        public \BcMath\Number $memberID = new \BcMath\Number(0),
        #[Reflection\Field(3, new Reflection\EnumT(\Etcdserverpb\AlarmType::class))]
        public \Etcdserverpb\AlarmType $alarm = \Etcdserverpb\AlarmType::NONE,
    ) {}
}
