<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class AlarmMember
{
    /**
     * @param \BcMath\Number $memberID memberID is the ID of the member associated with the raised alarm.
     * @param \Etcdserverpb\AlarmType $alarm alarm is the type of alarm which has been raised.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Uint64T::T)]
        public \BcMath\Number $memberID = new \BcMath\Number(0),
        #[Reflection\Field(2, new Reflection\EnumT(\Etcdserverpb\AlarmType::class))]
        public \Etcdserverpb\AlarmType $alarm = \Etcdserverpb\AlarmType::NONE,
    ) {}
}
