<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class AuthUserChangePasswordRequest
{
    /**
     * @param string $name name is the name of the user whose password is being changed.
     * @param string $password password is the new password for the user. Note that this field will be removed in the API layer.
     * @param string $hashedPassword hashedPassword is the new password for the user. Note that this field will be initialized in the API layer.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $password = '',
        #[Reflection\Field(3, Reflection\StringT::T)]
        public string $hashedPassword = '',
    ) {}
}
