<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class AuthUserGrantRoleRequest
{
    /**
     * @param string $user user is the name of the user which should be granted a given role.
     * @param string $role role is the name of the role to grant to the user.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $user = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $role = '',
    ) {}
}
