<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class AuthRoleGrantPermissionRequest
{
    /**
     * @param string $name name is the name of the role which will be granted the permission.
     * @param ?\Authpb\Permission $perm perm is the permission to grant to the role.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(2, new Reflection\ObjectT(\Authpb\Permission::class))]
        public ?\Authpb\Permission $perm = null,
    ) {}
}
