<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class AuthRoleRevokePermissionRequest
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $role = '',
        #[Reflection\Field(2, Reflection\BytesT::T)]
        public string $key = '',
        #[Reflection\Field(3, Reflection\BytesT::T)]
        public string $rangeEnd = '',
    ) {}
}
