<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class AuthUserAddRequest
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $password = '',
        #[Reflection\Field(3, new Reflection\ObjectT(\Authpb\UserAddOptions::class))]
        public ?\Authpb\UserAddOptions $options = null,
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $hashedPassword = '',
    ) {}
}
