<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class AuthClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * AuthEnable enables authentication.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function authEnable(
        \Etcdserverpb\AuthEnableRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthEnableResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthEnableRequest, \Etcdserverpb\AuthEnableResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/AuthEnable',
            output: \Etcdserverpb\AuthEnableResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * AuthDisable disables authentication.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function authDisable(
        \Etcdserverpb\AuthDisableRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthDisableResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthDisableRequest, \Etcdserverpb\AuthDisableResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/AuthDisable',
            output: \Etcdserverpb\AuthDisableResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * AuthStatus displays authentication status.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function authStatus(
        \Etcdserverpb\AuthStatusRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthStatusResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthStatusRequest, \Etcdserverpb\AuthStatusResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/AuthStatus',
            output: \Etcdserverpb\AuthStatusResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Authenticate processes an authenticate request.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function authenticate(
        \Etcdserverpb\AuthenticateRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthenticateResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthenticateRequest, \Etcdserverpb\AuthenticateResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/Authenticate',
            output: \Etcdserverpb\AuthenticateResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * UserAdd adds a new user. User name cannot be empty.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function userAdd(
        \Etcdserverpb\AuthUserAddRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthUserAddResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthUserAddRequest, \Etcdserverpb\AuthUserAddResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/UserAdd',
            output: \Etcdserverpb\AuthUserAddResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * UserGet gets detailed user information.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function userGet(
        \Etcdserverpb\AuthUserGetRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthUserGetResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthUserGetRequest, \Etcdserverpb\AuthUserGetResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/UserGet',
            output: \Etcdserverpb\AuthUserGetResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * UserList gets a list of all users.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function userList(
        \Etcdserverpb\AuthUserListRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthUserListResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthUserListRequest, \Etcdserverpb\AuthUserListResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/UserList',
            output: \Etcdserverpb\AuthUserListResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * UserDelete deletes a specified user.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function userDelete(
        \Etcdserverpb\AuthUserDeleteRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthUserDeleteResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthUserDeleteRequest, \Etcdserverpb\AuthUserDeleteResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/UserDelete',
            output: \Etcdserverpb\AuthUserDeleteResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * UserChangePassword changes the password of a specified user.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function userChangePassword(
        \Etcdserverpb\AuthUserChangePasswordRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthUserChangePasswordResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthUserChangePasswordRequest, \Etcdserverpb\AuthUserChangePasswordResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/UserChangePassword',
            output: \Etcdserverpb\AuthUserChangePasswordResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * UserGrantRole grants a role to a specified user.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function userGrantRole(
        \Etcdserverpb\AuthUserGrantRoleRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthUserGrantRoleResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthUserGrantRoleRequest, \Etcdserverpb\AuthUserGrantRoleResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/UserGrantRole',
            output: \Etcdserverpb\AuthUserGrantRoleResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * UserRevokeRole revokes a role of specified user.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function userRevokeRole(
        \Etcdserverpb\AuthUserRevokeRoleRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthUserRevokeRoleResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthUserRevokeRoleRequest, \Etcdserverpb\AuthUserRevokeRoleResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/UserRevokeRole',
            output: \Etcdserverpb\AuthUserRevokeRoleResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * RoleAdd adds a new role. Role name cannot be empty.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function roleAdd(
        \Etcdserverpb\AuthRoleAddRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthRoleAddResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthRoleAddRequest, \Etcdserverpb\AuthRoleAddResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/RoleAdd',
            output: \Etcdserverpb\AuthRoleAddResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * RoleGet gets detailed role information.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function roleGet(
        \Etcdserverpb\AuthRoleGetRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthRoleGetResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthRoleGetRequest, \Etcdserverpb\AuthRoleGetResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/RoleGet',
            output: \Etcdserverpb\AuthRoleGetResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * RoleList gets lists of all roles.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function roleList(
        \Etcdserverpb\AuthRoleListRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthRoleListResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthRoleListRequest, \Etcdserverpb\AuthRoleListResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/RoleList',
            output: \Etcdserverpb\AuthRoleListResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * RoleDelete deletes a specified role.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function roleDelete(
        \Etcdserverpb\AuthRoleDeleteRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthRoleDeleteResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthRoleDeleteRequest, \Etcdserverpb\AuthRoleDeleteResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/RoleDelete',
            output: \Etcdserverpb\AuthRoleDeleteResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * RoleGrantPermission grants a permission of a specified key or range to a specified role.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function roleGrantPermission(
        \Etcdserverpb\AuthRoleGrantPermissionRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthRoleGrantPermissionResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthRoleGrantPermissionRequest, \Etcdserverpb\AuthRoleGrantPermissionResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/RoleGrantPermission',
            output: \Etcdserverpb\AuthRoleGrantPermissionResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * RoleRevokePermission revokes a key or range permission of a specified role.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function roleRevokePermission(
        \Etcdserverpb\AuthRoleRevokePermissionRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AuthRoleRevokePermissionResponse {
        /** @var Client\Invoke<\Etcdserverpb\AuthRoleRevokePermissionRequest, \Etcdserverpb\AuthRoleRevokePermissionResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Auth/RoleRevokePermission',
            output: \Etcdserverpb\AuthRoleRevokePermissionResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
