<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class AuthStatusResponse
{
    /**
     * @param \BcMath\Number $authRevision authRevision is the current revision of auth store
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\BoolT::T)]
        public bool $enabled = false,
        #[Reflection\Field(3, Reflection\Uint64T::T)]
        public \BcMath\Number $authRevision = new \BcMath\Number(0),
    ) {}
}
