<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class ClusterClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * MemberAdd adds a member into the cluster.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function memberAdd(
        \Etcdserverpb\MemberAddRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\MemberAddResponse {
        /** @var Client\Invoke<\Etcdserverpb\MemberAddRequest, \Etcdserverpb\MemberAddResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Cluster/MemberAdd',
            type: \Etcdserverpb\MemberAddResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * MemberRemove removes an existing member from the cluster.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function memberRemove(
        \Etcdserverpb\MemberRemoveRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\MemberRemoveResponse {
        /** @var Client\Invoke<\Etcdserverpb\MemberRemoveRequest, \Etcdserverpb\MemberRemoveResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Cluster/MemberRemove',
            type: \Etcdserverpb\MemberRemoveResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * MemberUpdate updates the member configuration.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function memberUpdate(
        \Etcdserverpb\MemberUpdateRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\MemberUpdateResponse {
        /** @var Client\Invoke<\Etcdserverpb\MemberUpdateRequest, \Etcdserverpb\MemberUpdateResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Cluster/MemberUpdate',
            type: \Etcdserverpb\MemberUpdateResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * MemberList lists all the members in the cluster.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function memberList(
        \Etcdserverpb\MemberListRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\MemberListResponse {
        /** @var Client\Invoke<\Etcdserverpb\MemberListRequest, \Etcdserverpb\MemberListResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Cluster/MemberList',
            type: \Etcdserverpb\MemberListResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * MemberPromote promotes a member from raft learner (non-voting) to raft voting member.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function memberPromote(
        \Etcdserverpb\MemberPromoteRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\MemberPromoteResponse {
        /** @var Client\Invoke<\Etcdserverpb\MemberPromoteRequest, \Etcdserverpb\MemberPromoteResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Cluster/MemberPromote',
            type: \Etcdserverpb\MemberPromoteResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
