<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Compare
{
    /**
     * @param \Etcdserverpb\Compare\CompareResult $result result is logical comparison operation for this comparison.
     * @param \Etcdserverpb\Compare\CompareTarget $target target is the key-value field to inspect for the comparison.
     * @param string $key key is the subject key for the comparison operation.
     * @param string $rangeEnd range_end compares the given target to all keys in the range [key, range_end).
     * See RangeRequest for more details on key ranges.
     *
     * TODO: fill out with most of the rest of RangeRequest fields when needed.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Etcdserverpb\Compare\CompareResult::class))]
        public \Etcdserverpb\Compare\CompareResult $result = \Etcdserverpb\Compare\CompareResult::EQUAL,
        #[Reflection\Field(2, new Reflection\EnumT(\Etcdserverpb\Compare\CompareTarget::class))]
        public \Etcdserverpb\Compare\CompareTarget $target = \Etcdserverpb\Compare\CompareTarget::VERSION,
        #[Reflection\Field(3, Reflection\BytesT::T)]
        public string $key = '',
        #[Reflection\Field(64, Reflection\BytesT::T)]
        public string $rangeEnd = '',
        #[Reflection\OneOf([
            \Etcdserverpb\Compare\TargetUnionVersion::class,
            \Etcdserverpb\Compare\TargetUnionCreateRevision::class,
            \Etcdserverpb\Compare\TargetUnionModRevision::class,
            \Etcdserverpb\Compare\TargetUnionValue::class,
            \Etcdserverpb\Compare\TargetUnionLease::class,
        ])]
        public ?\Etcdserverpb\Compare\TargetUnion $targetUnion = null,
    ) {}
}
