<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * CompactionRequest compacts the key-value store up to a given revision. All superseded keys
 * with a revision less than the compaction revision will be removed.
 */
final readonly class CompactionRequest
{
    /**
     * @param int $revision revision is the key-value store revision for the compaction operation.
     * @param bool $physical physical is set so the RPC will wait until the compaction is physically
     * applied to the local database such that compacted entries are totally
     * removed from the backend database.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public int $revision = 0,
        #[Reflection\Field(2, Reflection\BoolT::T)]
        public bool $physical = false,
    ) {}
}
