<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class DeleteRangeResponse
{
    /**
     * @param int $deleted deleted is the number of keys deleted by the delete range request.
     * @param list<\Mvccpb\KeyValue> $prevKvs if prev_kv is set in the request, the previous key-value pairs will be returned.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public int $deleted = 0,
        #[Reflection\Field(3, new Reflection\ListT(new Reflection\ObjectT(\Mvccpb\KeyValue::class)))]
        public array $prevKvs = [],
    ) {}
}
