<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class DowngradeInfo
{
    /**
     * @param bool $enabled enabled indicates whether the cluster is enabled to downgrade.
     * @param string $targetVersion targetVersion is the target downgrade version.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BoolT::T)]
        public bool $enabled = false,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $targetVersion = '',
    ) {}
}
