<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class DowngradeResponse
{
    /**
     * @param string $version version is the current cluster version.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $version = '',
    ) {}
}
