<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class DowngradeRequest
{
    /**
     * @param \Etcdserverpb\DowngradeRequest\DowngradeAction $action action is the kind of downgrade request to issue. The action may
     * VALIDATE the target version, DOWNGRADE the cluster version,
     * or CANCEL the current downgrading job.
     * @param string $version version is the target version to downgrade.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Etcdserverpb\DowngradeRequest\DowngradeAction::class))]
        public \Etcdserverpb\DowngradeRequest\DowngradeAction $action = \Etcdserverpb\DowngradeRequest\DowngradeAction::VALIDATE,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $version = '',
    ) {}
}
