<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * DowngradeVersionTestRequest is used for test only. The version in
 * this request will be read as the WAL record version.If the downgrade
 * target version is less than this version, then the downgrade(online)
 * or migration(offline) isn't safe, so shouldn't be allowed.
 */
final readonly class DowngradeVersionTestRequest
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $ver = '',
    ) {}
}
