<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class HashKVRequest
{
    /**
     * @param \BcMath\Number $revision revision is the key-value store revision for the hash operation.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public \BcMath\Number $revision = new \BcMath\Number(0),
    ) {}
}
