<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class HashKVResponse
{
    /**
     * @param int $hash hash is the hash value computed from the responding member's MVCC keys up to a given revision.
     * @param \BcMath\Number $compactRevision compact_revision is the compacted revision of key-value store when hash begins.
     * @param \BcMath\Number $hashRevision hash_revision is the revision up to which the hash is calculated.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\Uint32T::T)]
        public int $hash = 0,
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public \BcMath\Number $compactRevision = new \BcMath\Number(0),
        #[Reflection\Field(4, Reflection\Int64T::T)]
        public \BcMath\Number $hashRevision = new \BcMath\Number(0),
    ) {}
}
