<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class KVClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * Range gets the keys in the range from the key-value store.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function range(
        \Etcdserverpb\RangeRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\RangeResponse {
        /** @var Client\Invoke<\Etcdserverpb\RangeRequest, \Etcdserverpb\RangeResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.KV/Range',
            type: \Etcdserverpb\RangeResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * RangeStream gets the keys in the range from the key-value store.
     *
     * This RPC is intentionally gRPC-only and does not provide a
     * grpc-gateway REST mapping, because streaming chunked responses
     * are not a good fit for standard JSON/REST semantics.
     *
     * @return Client\ServerStreamChannel<\Etcdserverpb\RangeRequest, \Etcdserverpb\RangeStreamResponse>
     */
    public function rangeStream(
        \Etcdserverpb\RangeRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\ServerStreamChannel {
        /** @var Client\Invoke<\Etcdserverpb\RangeRequest, \Etcdserverpb\RangeStreamResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.KV/RangeStream',
            type: \Etcdserverpb\RangeStreamResponse::class,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        $stream->send($request);
        $stream->close();

        return new Client\ServerStreamChannel($stream);
    }

    /**
     * Put puts the given key into the key-value store.
     * A put request increments the revision of the key-value store
     * and generates one event in the event history.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function put(
        \Etcdserverpb\PutRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\PutResponse {
        /** @var Client\Invoke<\Etcdserverpb\PutRequest, \Etcdserverpb\PutResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.KV/Put',
            type: \Etcdserverpb\PutResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * DeleteRange deletes the given range from the key-value store.
     * A delete request increments the revision of the key-value store
     * and generates a delete event in the event history for every deleted key.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function deleteRange(
        \Etcdserverpb\DeleteRangeRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\DeleteRangeResponse {
        /** @var Client\Invoke<\Etcdserverpb\DeleteRangeRequest, \Etcdserverpb\DeleteRangeResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.KV/DeleteRange',
            type: \Etcdserverpb\DeleteRangeResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Txn processes multiple requests in a single transaction.
     * A txn request increments the revision of the key-value store
     * and generates events with the same revision for every completed request.
     * It is not allowed to modify the same key several times within one txn.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function txn(
        \Etcdserverpb\TxnRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\TxnResponse {
        /** @var Client\Invoke<\Etcdserverpb\TxnRequest, \Etcdserverpb\TxnResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.KV/Txn',
            type: \Etcdserverpb\TxnResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Compact compacts the event history in the etcd key-value store. The key-value
     * store should be periodically compacted or the event history will continue to grow
     * indefinitely.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function compact(
        \Etcdserverpb\CompactionRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\CompactionResponse {
        /** @var Client\Invoke<\Etcdserverpb\CompactionRequest, \Etcdserverpb\CompactionResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.KV/Compact',
            type: \Etcdserverpb\CompactionResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
