<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseGrantRequest
{
    /**
     * @param int $TTL TTL is the advisory time-to-live in seconds. Expired lease will return -1.
     * @param int $ID ID is the requested ID for the lease. If ID is set to 0, the lessor chooses an ID.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public int $TTL = 0,
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public int $ID = 0,
    ) {}
}
