<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseTimeToLiveResponse
{
    /**
     * @param int $ID ID is the lease ID from the keep alive request.
     * @param int $TTL TTL is the remaining TTL in seconds for the lease; the lease will expire in under TTL+1 seconds.
     * @param int $grantedTTL GrantedTTL is the initial granted time in seconds upon lease creation/renewal.
     * @param list<string> $keys Keys is the list of keys attached to this lease.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public int $ID = 0,
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public int $TTL = 0,
        #[Reflection\Field(4, Reflection\Int64T::T)]
        public int $grantedTTL = 0,
        #[Reflection\Field(5, new Reflection\ListT(Reflection\BytesT::T))]
        public array $keys = [],
    ) {}
}
