<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseTimeToLiveRequest
{
    /**
     * @param int $ID ID is the lease ID for the lease.
     * @param bool $keys keys is true to query all the keys attached to this lease.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public int $ID = 0,
        #[Reflection\Field(2, Reflection\BoolT::T)]
        public bool $keys = false,
    ) {}
}
