<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseCheckpoint
{
    /**
     * @param \BcMath\Number $ID ID is the lease ID to checkpoint.
     * @param \BcMath\Number $remainingTTL Remaining_TTL is the remaining time until expiry of the lease.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public \BcMath\Number $ID = new \BcMath\Number(0),
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public \BcMath\Number $remainingTTL = new \BcMath\Number(0),
    ) {}
}
