<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class LeaseClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * LeaseGrant creates a lease which expires if the server does not receive a keepAlive
     * within a given time to live period. All keys attached to the lease will be expired and
     * deleted if the lease expires. Each expired key generates a delete event in the event history.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function leaseGrant(
        \Etcdserverpb\LeaseGrantRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\LeaseGrantResponse {
        /** @var Client\Invoke<\Etcdserverpb\LeaseGrantRequest, \Etcdserverpb\LeaseGrantResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Lease/LeaseGrant',
            type: \Etcdserverpb\LeaseGrantResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * LeaseRevoke revokes a lease. All keys attached to the lease will expire and be deleted.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function leaseRevoke(
        \Etcdserverpb\LeaseRevokeRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\LeaseRevokeResponse {
        /** @var Client\Invoke<\Etcdserverpb\LeaseRevokeRequest, \Etcdserverpb\LeaseRevokeResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Lease/LeaseRevoke',
            type: \Etcdserverpb\LeaseRevokeResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * LeaseKeepAlive keeps the lease alive by streaming keep alive requests from the client
     * to the server and streaming keep alive responses from the server to the client.
     *
     * @return Client\BidirectionalStreamChannel<\Etcdserverpb\LeaseKeepAliveRequest, \Etcdserverpb\LeaseKeepAliveResponse>
     */
    public function leaseKeepAlive(
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\BidirectionalStreamChannel {
        /** @var Client\Invoke<\Etcdserverpb\LeaseKeepAliveRequest, \Etcdserverpb\LeaseKeepAliveResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Lease/LeaseKeepAlive',
            type: \Etcdserverpb\LeaseKeepAliveResponse::class,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        return new Client\BidirectionalStreamChannel($stream);
    }

    /**
     * LeaseTimeToLive retrieves lease information.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function leaseTimeToLive(
        \Etcdserverpb\LeaseTimeToLiveRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\LeaseTimeToLiveResponse {
        /** @var Client\Invoke<\Etcdserverpb\LeaseTimeToLiveRequest, \Etcdserverpb\LeaseTimeToLiveResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Lease/LeaseTimeToLive',
            type: \Etcdserverpb\LeaseTimeToLiveResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * LeaseLeases lists all existing leases.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function leaseLeases(
        \Etcdserverpb\LeaseLeasesRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\LeaseLeasesResponse {
        /** @var Client\Invoke<\Etcdserverpb\LeaseLeasesRequest, \Etcdserverpb\LeaseLeasesResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Lease/LeaseLeases',
            type: \Etcdserverpb\LeaseLeasesResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
