<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseKeepAliveResponse
{
    /**
     * @param \BcMath\Number $iD ID is the lease ID from the keep alive request.
     * @param \BcMath\Number $tTL TTL is the new time-to-live for the lease.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public \BcMath\Number $iD = new \BcMath\Number(0),
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public \BcMath\Number $tTL = new \BcMath\Number(0),
    ) {}
}
