<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseRevokeRequest
{
    /**
     * @param \BcMath\Number $ID ID is the lease ID to revoke. When the ID is revoked, all associated keys will be deleted.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public \BcMath\Number $ID = new \BcMath\Number(0),
    ) {}
}
