<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseGrantRequest
{
    /**
     * @param \BcMath\Number $tTL TTL is the advisory time-to-live in seconds. Expired lease will return -1.
     * @param \BcMath\Number $iD ID is the requested ID for the lease. If ID is set to 0, the lessor chooses an ID.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public \BcMath\Number $tTL = new \BcMath\Number(0),
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public \BcMath\Number $iD = new \BcMath\Number(0),
    ) {}
}
