<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseKeepAliveRequest
{
    /**
     * @param int $ID ID is the lease ID for the lease to keep alive.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public int $ID = 0,
    ) {}
}
