<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseRevokeRequest
{
    /**
     * @param int $ID ID is the lease ID to revoke. When the ID is revoked, all associated keys will be deleted.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public int $ID = 0,
    ) {}
}
