<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaseGrantResponse
{
    /**
     * @param int $ID ID is the lease ID for the granted lease.
     * @param int $TTL TTL is the server chosen lease time-to-live in seconds.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public int $ID = 0,
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public int $TTL = 0,
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $error = '',
    ) {}
}
