<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class MaintenanceClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * Alarm activates, deactivates, and queries alarms regarding cluster health.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function alarm(
        \Etcdserverpb\AlarmRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\AlarmResponse {
        /** @var Client\Invoke<\Etcdserverpb\AlarmRequest, \Etcdserverpb\AlarmResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Maintenance/Alarm',
            type: \Etcdserverpb\AlarmResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Status gets the status of the member.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function status(
        \Etcdserverpb\StatusRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\StatusResponse {
        /** @var Client\Invoke<\Etcdserverpb\StatusRequest, \Etcdserverpb\StatusResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Maintenance/Status',
            type: \Etcdserverpb\StatusResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Defragment defragments a member's backend database to recover storage space.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function defragment(
        \Etcdserverpb\DefragmentRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\DefragmentResponse {
        /** @var Client\Invoke<\Etcdserverpb\DefragmentRequest, \Etcdserverpb\DefragmentResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Maintenance/Defragment',
            type: \Etcdserverpb\DefragmentResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Hash computes the hash of whole backend keyspace,
     * including key, lease, and other buckets in storage.
     * This is designed for testing ONLY!
     * Do not rely on this in production with ongoing transactions,
     * since Hash operation does not hold MVCC locks.
     * Use "HashKV" API instead for "key" bucket consistency checks.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function hash(
        \Etcdserverpb\HashRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\HashResponse {
        /** @var Client\Invoke<\Etcdserverpb\HashRequest, \Etcdserverpb\HashResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Maintenance/Hash',
            type: \Etcdserverpb\HashResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * HashKV computes the hash of all MVCC keys up to a given revision.
     * It only iterates "key" bucket in backend storage.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function hashKV(
        \Etcdserverpb\HashKVRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\HashKVResponse {
        /** @var Client\Invoke<\Etcdserverpb\HashKVRequest, \Etcdserverpb\HashKVResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Maintenance/HashKV',
            type: \Etcdserverpb\HashKVResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Snapshot sends a snapshot of the entire backend from a member over a stream to a client.
     *
     * @return Client\ServerStreamChannel<\Etcdserverpb\SnapshotRequest, \Etcdserverpb\SnapshotResponse>
     */
    public function snapshot(
        \Etcdserverpb\SnapshotRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\ServerStreamChannel {
        /** @var Client\Invoke<\Etcdserverpb\SnapshotRequest, \Etcdserverpb\SnapshotResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Maintenance/Snapshot',
            type: \Etcdserverpb\SnapshotResponse::class,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        $stream->send($request);
        $stream->close();

        return new Client\ServerStreamChannel($stream);
    }

    /**
     * MoveLeader requests current leader node to transfer its leadership to transferee.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function moveLeader(
        \Etcdserverpb\MoveLeaderRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\MoveLeaderResponse {
        /** @var Client\Invoke<\Etcdserverpb\MoveLeaderRequest, \Etcdserverpb\MoveLeaderResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Maintenance/MoveLeader',
            type: \Etcdserverpb\MoveLeaderResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Downgrade requests downgrades, verifies feasibility or cancels downgrade
     * on the cluster version.
     * Supported since etcd 3.5.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function downgrade(
        \Etcdserverpb\DowngradeRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Etcdserverpb\DowngradeResponse {
        /** @var Client\Invoke<\Etcdserverpb\DowngradeRequest, \Etcdserverpb\DowngradeResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Maintenance/Downgrade',
            type: \Etcdserverpb\DowngradeResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
