<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MemberRemoveRequest
{
    /**
     * @param \BcMath\Number $ID ID is the member ID of the member to remove.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Uint64T::T)]
        public \BcMath\Number $ID = new \BcMath\Number(0),
    ) {}
}
