<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Member
{
    /**
     * @param \BcMath\Number $ID ID is the member ID for this member.
     * @param string $name name is the human-readable name of the member. If the member is not started, the name will be an empty string.
     * @param list<string> $peerURLs peerURLs is the list of URLs the member exposes to the cluster for communication.
     * @param list<string> $clientURLs clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * @param bool $isLearner isLearner indicates if the member is raft learner.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Uint64T::T)]
        public \BcMath\Number $ID = new \BcMath\Number(0),
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(3, new Reflection\ListT(Reflection\StringT::T))]
        public array $peerURLs = [],
        #[Reflection\Field(4, new Reflection\ListT(Reflection\StringT::T))]
        public array $clientURLs = [],
        #[Reflection\Field(5, Reflection\BoolT::T)]
        public bool $isLearner = false,
    ) {}
}
