<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MemberUpdateRequest
{
    /**
     * @param \BcMath\Number $ID ID is the member ID of the member to update.
     * @param list<string> $peerURLs peerURLs is the new list of URLs the member will use to communicate with the cluster.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Uint64T::T)]
        public \BcMath\Number $ID = new \BcMath\Number(0),
        #[Reflection\Field(2, new Reflection\ListT(Reflection\StringT::T))]
        public array $peerURLs = [],
    ) {}
}
