<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MemberAddRequest
{
    /**
     * @param list<string> $peerURLs peerURLs is the list of URLs the added member will use to communicate with the cluster.
     * @param bool $isLearner isLearner indicates if the added member is raft learner.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(Reflection\StringT::T))]
        public array $peerURLs = [],
        #[Reflection\Field(2, Reflection\BoolT::T)]
        public bool $isLearner = false,
    ) {}
}
