<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class PutRequest
{
    /**
     * @param string $key key is the key, in bytes, to put into the key-value store.
     * @param string $value value is the value, in bytes, to associate with the key in the key-value store.
     * @param int $lease lease is the lease ID to associate with the key in the key-value store. A lease
     * value of 0 indicates no lease.
     * @param bool $prevKv If prev_kv is set, etcd gets the previous key-value pair before changing it.
     * The previous key-value pair will be returned in the put response.
     * @param bool $ignoreValue If ignore_value is set, etcd updates the key using its current value.
     * Returns an error if the key does not exist.
     * @param bool $ignoreLease If ignore_lease is set, etcd updates the key using its current lease.
     * Returns an error if the key does not exist.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $key = '',
        #[Reflection\Field(2, Reflection\BytesT::T)]
        public string $value = '',
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public int $lease = 0,
        #[Reflection\Field(4, Reflection\BoolT::T)]
        public bool $prevKv = false,
        #[Reflection\Field(5, Reflection\BoolT::T)]
        public bool $ignoreValue = false,
        #[Reflection\Field(6, Reflection\BoolT::T)]
        public bool $ignoreLease = false,
    ) {}
}
