<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class PutResponse
{
    /**
     * @param ?\Mvccpb\KeyValue $prevKv if prev_kv is set in the request, the previous key-value pair will be returned.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, new Reflection\ObjectT(\Mvccpb\KeyValue::class))]
        public ?\Mvccpb\KeyValue $prevKv = null,
    ) {}
}
