<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class RangeRequest
{
    /**
     * @param string $key key is the first key for the range. If range_end is not given, the request only looks up key.
     * @param string $rangeEnd range_end is the upper bound on the requested range [key, range_end).
     * If range_end is '\0', the range is all keys >= key.
     * If range_end is key plus one (e.g., "aa"+1 == "ab", "a\xff"+1 == "b"),
     * then the range request gets all keys prefixed with key.
     * If both key and range_end are '\0', then the range request returns all keys.
     * @param int $limit limit is a limit on the number of keys returned for the request. When limit is set to 0,
     * it is treated as no limit.
     * @param int $revision revision is the point-in-time of the key-value store to use for the range.
     * If revision is less or equal to zero, the range is over the newest key-value store.
     * If the revision has been compacted, ErrCompacted is returned as a response.
     * @param \Etcdserverpb\RangeRequest\SortOrder $sortOrder sort_order is the order for returned sorted results.
     * @param \Etcdserverpb\RangeRequest\SortTarget $sortTarget sort_target is the key-value field to use for sorting.
     * @param bool $serializable serializable sets the range request to use serializable member-local reads.
     * Range requests are linearizable by default; linearizable requests have higher
     * latency and lower throughput than serializable requests but reflect the current
     * consensus of the cluster. For better performance, in exchange for possible stale reads,
     * a serializable range request is served locally without needing to reach consensus
     * with other nodes in the cluster.
     * @param bool $keysOnly keys_only when set returns only the keys and not the values.
     * @param bool $countOnly count_only when set returns only the count of the keys in the range.
     * @param int $minModRevision min_mod_revision is the lower bound for returned key mod revisions; all keys with
     * lesser mod revisions will be filtered away.
     * @param int $maxModRevision max_mod_revision is the upper bound for returned key mod revisions; all keys with
     * greater mod revisions will be filtered away.
     * @param int $minCreateRevision min_create_revision is the lower bound for returned key create revisions; all keys with
     * lesser create revisions will be filtered away.
     * @param int $maxCreateRevision max_create_revision is the upper bound for returned key create revisions; all keys with
     * greater create revisions will be filtered away.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $key = '',
        #[Reflection\Field(2, Reflection\BytesT::T)]
        public string $rangeEnd = '',
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public int $limit = 0,
        #[Reflection\Field(4, Reflection\Int64T::T)]
        public int $revision = 0,
        #[Reflection\Field(5, new Reflection\EnumT(\Etcdserverpb\RangeRequest\SortOrder::class))]
        public \Etcdserverpb\RangeRequest\SortOrder $sortOrder = \Etcdserverpb\RangeRequest\SortOrder::NONE,
        #[Reflection\Field(6, new Reflection\EnumT(\Etcdserverpb\RangeRequest\SortTarget::class))]
        public \Etcdserverpb\RangeRequest\SortTarget $sortTarget = \Etcdserverpb\RangeRequest\SortTarget::KEY,
        #[Reflection\Field(7, Reflection\BoolT::T)]
        public bool $serializable = false,
        #[Reflection\Field(8, Reflection\BoolT::T)]
        public bool $keysOnly = false,
        #[Reflection\Field(9, Reflection\BoolT::T)]
        public bool $countOnly = false,
        #[Reflection\Field(10, Reflection\Int64T::T)]
        public int $minModRevision = 0,
        #[Reflection\Field(11, Reflection\Int64T::T)]
        public int $maxModRevision = 0,
        #[Reflection\Field(12, Reflection\Int64T::T)]
        public int $minCreateRevision = 0,
        #[Reflection\Field(13, Reflection\Int64T::T)]
        public int $maxCreateRevision = 0,
    ) {}
}
