<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * RangeStreamResponse is the response for the RangeStream RPC.
 */
final readonly class RangeStreamResponse
{
    /**
     * @param ?\Etcdserverpb\RangeResponse $rangeResponse range_response is a partial response for the KV.RangeStream RPC.
     * The result of proto.Merge() applied on all responses should result in the
     * same RangeResponse response as to the Range() method.
     *
     * Field population across chunks:
     *   - kvs: each chunk carries a disjoint slice of the result. Concatenating
     *     them in order yields the full key set.
     *   - header, more, count: set only on the final chunk. Non-merge clients
     *     can rely on io.EOF (end of stream) to detect completion. These
     *     fields are provided for clients that merge all responses into a
     *     single RangeResponse.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\RangeResponse::class))]
        public ?\Etcdserverpb\RangeResponse $rangeResponse = null,
    ) {}
}
