<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class RangeResponse
{
    /**
     * @param list<\Mvccpb\KeyValue> $kvs kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     * @param bool $more more indicates if there are more keys to return in the requested range.
     * @param int $count count is set to the actual number of keys within the range when requested.
     * Unlike Kvs, it is unaffected by limits and filters (e.g., Min/Max, Create/Modify, Revisions)
     * and reflects the full count within the specified range.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Mvccpb\KeyValue::class)))]
        public array $kvs = [],
        #[Reflection\Field(3, Reflection\BoolT::T)]
        public bool $more = false,
        #[Reflection\Field(4, Reflection\Int64T::T)]
        public int $count = 0,
    ) {}
}
