<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class RequestOp
{
    public function __construct(
        #[Reflection\OneOf([
            \Etcdserverpb\RequestOp\RequestRequestRange::class,
            \Etcdserverpb\RequestOp\RequestRequestPut::class,
            \Etcdserverpb\RequestOp\RequestRequestDeleteRange::class,
            \Etcdserverpb\RequestOp\RequestRequestTxn::class,
        ])]
        public ?\Etcdserverpb\RequestOp\Request $request = null,
    ) {}
}
