<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class ResponseHeader
{
    /**
     * @param \BcMath\Number $clusterId cluster_id is the ID of the cluster which sent the response.
     * @param \BcMath\Number $memberId member_id is the ID of the member which sent the response.
     * @param int $revision revision is the key-value store revision when the request was applied, and it's
     * unset (so 0) in case of calls not interacting with key-value store.
     * For watch progress responses, the header.revision indicates progress. All future events
     * received in this stream are guaranteed to have a higher revision number than the
     * header.revision number.
     * @param \BcMath\Number $raftTerm raft_term is the raft term when the request was applied.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Uint64T::T)]
        public \BcMath\Number $clusterId = new \BcMath\Number(0),
        #[Reflection\Field(2, Reflection\Uint64T::T)]
        public \BcMath\Number $memberId = new \BcMath\Number(0),
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public int $revision = 0,
        #[Reflection\Field(4, Reflection\Uint64T::T)]
        public \BcMath\Number $raftTerm = new \BcMath\Number(0),
    ) {}
}
