<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class ResponseOp
{
    public function __construct(
        #[Reflection\OneOf([
            \Etcdserverpb\ResponseOp\ResponseResponseRange::class,
            \Etcdserverpb\ResponseOp\ResponseResponsePut::class,
            \Etcdserverpb\ResponseOp\ResponseResponseDeleteRange::class,
            \Etcdserverpb\ResponseOp\ResponseResponseTxn::class,
        ])]
        public ?\Etcdserverpb\ResponseOp\Response $response = null,
    ) {}
}
