<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class SnapshotResponse
{
    /**
     * @param ?\Etcdserverpb\ResponseHeader $header header has the current key-value store information. The first header in the snapshot
     * stream indicates the point in time of the snapshot.
     * @param \BcMath\Number $remainingBytes remaining_bytes is the number of blob bytes to be sent after this message
     * @param string $blob blob contains the next chunk of the snapshot in the snapshot stream.
     * @param string $version local version of server that created the snapshot.
     * In cluster with binaries with different version, each cluster can return different result.
     * Informs which etcd server version should be used when restoring the snapshot.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\Uint64T::T)]
        public \BcMath\Number $remainingBytes = new \BcMath\Number(0),
        #[Reflection\Field(3, Reflection\BytesT::T)]
        public string $blob = '',
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $version = '',
    ) {}
}
