<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class StatusResponse
{
    /**
     * @param string $version version is the cluster protocol version used by the responding member.
     * @param int $dbSize dbSize is the size of the backend database physically allocated, in bytes, of the responding member.
     * @param \BcMath\Number $leader leader is the member ID which the responding member believes is the current leader.
     * @param \BcMath\Number $raftIndex raftIndex is the current raft committed index of the responding member.
     * @param \BcMath\Number $raftTerm raftTerm is the current raft term of the responding member.
     * @param \BcMath\Number $raftAppliedIndex raftAppliedIndex is the current raft applied index of the responding member.
     * @param list<string> $errors errors contains alarm/health information and status.
     * @param int $dbSizeInUse dbSizeInUse is the size of the backend database logically in use, in bytes, of the responding member.
     * @param bool $isLearner isLearner indicates if the member is raft learner.
     * @param string $storageVersion storageVersion is the version of the db file. It might be updated with delay in relationship to the target cluster version.
     * @param int $dbSizeQuota dbSizeQuota is the configured etcd storage quota in bytes (the value passed to etcd instance by flag --quota-backend-bytes)
     * @param ?\Etcdserverpb\DowngradeInfo $downgradeInfo downgradeInfo indicates if there is downgrade process.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $version = '',
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public int $dbSize = 0,
        #[Reflection\Field(4, Reflection\Uint64T::T)]
        public \BcMath\Number $leader = new \BcMath\Number(0),
        #[Reflection\Field(5, Reflection\Uint64T::T)]
        public \BcMath\Number $raftIndex = new \BcMath\Number(0),
        #[Reflection\Field(6, Reflection\Uint64T::T)]
        public \BcMath\Number $raftTerm = new \BcMath\Number(0),
        #[Reflection\Field(7, Reflection\Uint64T::T)]
        public \BcMath\Number $raftAppliedIndex = new \BcMath\Number(0),
        #[Reflection\Field(8, new Reflection\ListT(Reflection\StringT::T))]
        public array $errors = [],
        #[Reflection\Field(9, Reflection\Int64T::T)]
        public int $dbSizeInUse = 0,
        #[Reflection\Field(10, Reflection\BoolT::T)]
        public bool $isLearner = false,
        #[Reflection\Field(11, Reflection\StringT::T)]
        public string $storageVersion = '',
        #[Reflection\Field(12, Reflection\Int64T::T)]
        public int $dbSizeQuota = 0,
        #[Reflection\Field(13, new Reflection\ObjectT(\Etcdserverpb\DowngradeInfo::class))]
        public ?\Etcdserverpb\DowngradeInfo $downgradeInfo = null,
    ) {}
}
