<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * From google paxosdb paper:
 * Our implementation hinges around a powerful primitive which we call MultiOp. All other database
 * operations except for iteration are implemented as a single call to MultiOp. A MultiOp is applied atomically
 * and consists of three components:
 * 1. A list of tests called guard. Each test in guard checks a single entry in the database. It may check
 * for the absence or presence of a value, or compare with a given value. Two different tests in the guard
 * may apply to the same or different entries in the database. All tests in the guard are applied and
 * MultiOp returns the results. If all tests are true, MultiOp executes t op (see item 2 below), otherwise
 * it executes f op (see item 3 below).
 * 2. A list of database operations called t op. Each operation in the list is either an insert, delete, or
 * lookup operation, and applies to a single database entry. Two different operations in the list may apply
 * to the same or different entries in the database. These operations are executed
 * if guard evaluates to
 * true.
 * 3. A list of database operations called f op. Like t op, but executed if guard evaluates to false.
 */
final readonly class TxnRequest
{
    /**
     * @param list<\Etcdserverpb\Compare> $compare compare is a list of predicates representing a conjunction of terms.
     * If the comparisons succeed, then the success requests will be processed in order,
     * and the response will contain their respective responses in order.
     * If the comparisons fail, then the failure requests will be processed in order,
     * and the response will contain their respective responses in order.
     * @param list<\Etcdserverpb\RequestOp> $success success is a list of requests which will be applied when compare evaluates to true.
     * @param list<\Etcdserverpb\RequestOp> $failure failure is a list of requests which will be applied when compare evaluates to false.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(new Reflection\ObjectT(\Etcdserverpb\Compare::class)))]
        public array $compare = [],
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Etcdserverpb\RequestOp::class)))]
        public array $success = [],
        #[Reflection\Field(3, new Reflection\ListT(new Reflection\ObjectT(\Etcdserverpb\RequestOp::class)))]
        public array $failure = [],
    ) {}
}
