<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TxnResponse
{
    /**
     * @param bool $succeeded succeeded is set to true if the compare evaluated to true or false otherwise.
     * @param list<\Etcdserverpb\ResponseOp> $responses responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\BoolT::T)]
        public bool $succeeded = false,
        #[Reflection\Field(3, new Reflection\ListT(new Reflection\ObjectT(\Etcdserverpb\ResponseOp::class)))]
        public array $responses = [],
    ) {}
}
