<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class WatchCancelRequest
{
    /**
     * @param \BcMath\Number $watchId watch_id is the watcher id to cancel so that no more events are transmitted.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public \BcMath\Number $watchId = new \BcMath\Number(0),
    ) {}
}
