<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

/**
 * @api
 *
 * Requests the a watch stream progress status be sent in the watch response stream as soon as
 * possible.
 */
final readonly class WatchProgressRequest {}
