<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class WatchRequest
{
    public function __construct(
        #[Reflection\OneOf([
            \Etcdserverpb\WatchRequest\RequestUnionCreateRequest::class,
            \Etcdserverpb\WatchRequest\RequestUnionCancelRequest::class,
            \Etcdserverpb\WatchRequest\RequestUnionProgressRequest::class,
        ])]
        public ?\Etcdserverpb\WatchRequest\RequestUnion $requestUnion = null,
    ) {}
}
