<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class WatchCreateRequest
{
    /**
     * @param string $key key is the key to register for watching.
     * @param string $rangeEnd range_end is the end of the range [key, range_end) to watch. If range_end is not given,
     * only the key argument is watched. If range_end is equal to '\0', all keys greater than
     * or equal to the key argument are watched.
     * If the range_end is one bit larger than the given key,
     * then all keys with the prefix (the given key) will be watched.
     * @param int $startRevision start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
     * @param bool $progressNotify progress_notify is set so that the etcd server will periodically send a WatchResponse with
     * no events to the new watcher if there are no recent events. It is useful when clients
     * wish to recover a disconnected watcher starting from a recent known revision.
     * The etcd server may decide how often it will send notifications based on current load.
     * @param list<\Etcdserverpb\WatchCreateRequest\FilterType> $filters filters filter the events at server side before it sends back to the watcher.
     * @param bool $prevKv If prev_kv is set, created watcher gets the previous KV before the event happens.
     * If the previous KV is already compacted, nothing will be returned.
     * @param int $watchId If watch_id is provided and non-zero, it will be assigned to this watcher.
     * Since creating a watcher in etcd is not a synchronous operation,
     * this can be used ensure that ordering is correct when creating multiple
     * watchers on the same stream. Creating a watcher with an ID already in
     * use on the stream will cause an error to be returned.
     * @param bool $fragment fragment enables splitting large revisions into multiple watch responses.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $key = '',
        #[Reflection\Field(2, Reflection\BytesT::T)]
        public string $rangeEnd = '',
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public int $startRevision = 0,
        #[Reflection\Field(4, Reflection\BoolT::T)]
        public bool $progressNotify = false,
        #[Reflection\Field(5, new Reflection\ListT(new Reflection\EnumT(\Etcdserverpb\WatchCreateRequest\FilterType::class)))]
        public array $filters = [],
        #[Reflection\Field(6, Reflection\BoolT::T)]
        public bool $prevKv = false,
        #[Reflection\Field(7, Reflection\Int64T::T)]
        public int $watchId = 0,
        #[Reflection\Field(8, Reflection\BoolT::T)]
        public bool $fragment = false,
    ) {}
}
