<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc;
use Thesis\Grpc\Client;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class WatchClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * Watch watches for events happening or that have happened. Both input and output
     * are streams; the input stream is for creating and canceling watchers and the output
     * stream sends events. One watch RPC can watch on multiple key ranges, streaming events
     * for several watches at once. The entire event history can be watched starting from the
     * last compaction revision.
     *
     * @return Client\BidirectionalStreamChannel<\Etcdserverpb\WatchRequest, \Etcdserverpb\WatchResponse>
     */
    public function watch(
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\BidirectionalStreamChannel {
        /** @var Client\Invoke<\Etcdserverpb\WatchRequest, \Etcdserverpb\WatchResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/etcdserverpb.Watch/Watch',
            output: \Etcdserverpb\WatchResponse::class,
            type: Grpc\RpcType::BidirectionalStream,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        return new Client\BidirectionalStreamChannel($stream);
    }
}
