<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class WatchResponse
{
    /**
     * @param int $watchId watch_id is the ID of the watcher that corresponds to the response.
     * @param bool $created created is set to true if the response is for a create watch request.
     * The client should record the watch_id and expect to receive events for
     * the created watcher from the same stream.
     * All events sent to the created watcher will attach with the same watch_id.
     * @param bool $canceled canceled is set to true if the response is for a cancel watch request
     * or if the start_revision has already been compacted.
     * No further events will be sent to the canceled watcher.
     * @param int $compactRevision compact_revision is set to the minimum index if a watcher tries to watch
     * at a compacted index.
     *
     * This happens when creating a watcher at a compacted revision or the watcher cannot
     * catch up with the progress of the key-value store.
     *
     * The client should treat the watcher as canceled and should not try to create any
     * watcher with the same start_revision again.
     * @param string $cancelReason cancel_reason indicates the reason for canceling the watcher.
     * @param bool $fragment framgment is true if large watch response was split over multiple responses.
     * @param list<\Mvccpb\Event> $events
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public int $watchId = 0,
        #[Reflection\Field(3, Reflection\BoolT::T)]
        public bool $created = false,
        #[Reflection\Field(4, Reflection\BoolT::T)]
        public bool $canceled = false,
        #[Reflection\Field(5, Reflection\Int64T::T)]
        public int $compactRevision = 0,
        #[Reflection\Field(6, Reflection\StringT::T)]
        public string $cancelReason = '',
        #[Reflection\Field(7, Reflection\BoolT::T)]
        public bool $fragment = false,
        #[Reflection\Field(11, new Reflection\ListT(new Reflection\ObjectT(\Mvccpb\Event::class)))]
        public array $events = [],
    ) {}
}
