<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3election/v3electionpb/v3election.proto
 */

declare(strict_types=1);

namespace V3electionpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class CampaignRequest
{
    /**
     * @param string $name name is the election's identifier for the campaign.
     * @param \BcMath\Number $lease lease is the ID of the lease attached to leadership of the election. If the
     * lease expires or is revoked before resigning leadership, then the
     * leadership is transferred to the next campaigner, if any.
     * @param string $value value is the initial proclaimed value set when the campaigner wins the
     * election.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $name = '',
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public \BcMath\Number $lease = new \BcMath\Number(0),
        #[Reflection\Field(3, Reflection\BytesT::T)]
        public string $value = '',
    ) {}
}
