<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3election/v3electionpb/v3election.proto
 */

declare(strict_types=1);

namespace V3electionpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class CampaignResponse
{
    /**
     * @param ?\V3electionpb\LeaderKey $leader leader describes the resources used for holding leadereship of the election.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\ResponseHeader::class))]
        public ?\Etcdserverpb\ResponseHeader $header = null,
        #[Reflection\Field(2, new Reflection\ObjectT(\V3electionpb\LeaderKey::class))]
        public ?\V3electionpb\LeaderKey $leader = null,
    ) {}
}
