<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3election/v3electionpb/v3election.proto
 */

declare(strict_types=1);

namespace V3electionpb;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 *
 * The election service exposes client-side election facilities as a gRPC interface.
 */
final readonly class ElectionClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * Campaign waits to acquire leadership in an election, returning a LeaderKey
     * representing the leadership if successful. The LeaderKey can then be used
     * to issue new values on the election, transactionally guard API requests on
     * leadership still being held, and resign from the election.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function campaign(
        \V3electionpb\CampaignRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \V3electionpb\CampaignResponse {
        /** @var Client\Invoke<\V3electionpb\CampaignRequest, \V3electionpb\CampaignResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/v3electionpb.Election/Campaign',
            type: \V3electionpb\CampaignResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Proclaim updates the leader's posted value with a new value.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function proclaim(
        \V3electionpb\ProclaimRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \V3electionpb\ProclaimResponse {
        /** @var Client\Invoke<\V3electionpb\ProclaimRequest, \V3electionpb\ProclaimResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/v3electionpb.Election/Proclaim',
            type: \V3electionpb\ProclaimResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Leader returns the current election proclamation, if any.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function leader(
        \V3electionpb\LeaderRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \V3electionpb\LeaderResponse {
        /** @var Client\Invoke<\V3electionpb\LeaderRequest, \V3electionpb\LeaderResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/v3electionpb.Election/Leader',
            type: \V3electionpb\LeaderResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Observe streams election proclamations in-order as made by the election's
     * elected leaders.
     *
     * @return Client\ServerStreamChannel<\V3electionpb\LeaderRequest, \V3electionpb\LeaderResponse>
     */
    public function observe(
        \V3electionpb\LeaderRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\ServerStreamChannel {
        /** @var Client\Invoke<\V3electionpb\LeaderRequest, \V3electionpb\LeaderResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/v3electionpb.Election/Observe',
            type: \V3electionpb\LeaderResponse::class,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        $stream->send($request);
        $stream->close();

        return new Client\ServerStreamChannel($stream);
    }

    /**
     * Resign releases election leadership so other campaigners may acquire
     * leadership on the election.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function resign(
        \V3electionpb\ResignRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \V3electionpb\ResignResponse {
        /** @var Client\Invoke<\V3electionpb\ResignRequest, \V3electionpb\ResignResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/v3electionpb.Election/Resign',
            type: \V3electionpb\ResignResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
