<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3election/v3electionpb/v3election.proto
 */

declare(strict_types=1);

namespace V3electionpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LeaderKey
{
    /**
     * @param string $name name is the election identifier that corresponds to the leadership key.
     * @param string $key key is an opaque key representing the ownership of the election. If the key
     * is deleted, then leadership is lost.
     * @param int $rev rev is the creation revision of the key. It can be used to test for ownership
     * of an election during transactions by testing the key's creation revision
     * matches rev.
     * @param int $lease lease is the lease ID of the election leader.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $name = '',
        #[Reflection\Field(2, Reflection\BytesT::T)]
        public string $key = '',
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public int $rev = 0,
        #[Reflection\Field(4, Reflection\Int64T::T)]
        public int $lease = 0,
    ) {}
}
