<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/server/etcdserver/api/v3election/v3electionpb/v3election.proto
 */

declare(strict_types=1);

namespace V3electionpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class ResignRequest
{
    /**
     * @param ?\V3electionpb\LeaderKey $leader leader is the leadership to relinquish by resignation.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\V3electionpb\LeaderKey::class))]
        public ?\V3electionpb\LeaderKey $leader = null,
    ) {}
}
