<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/mvccpb/kv.proto
 */

declare(strict_types=1);

namespace Mvccpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Event
{
    /**
     * @param \Mvccpb\Event\EventType $type type is the kind of event. If type is a PUT, it indicates
     * new data has been stored to the key. If type is a DELETE,
     * it indicates the key was deleted.
     * @param ?\Mvccpb\KeyValue $kv kv holds the KeyValue for the event.
     * A PUT event contains current kv pair.
     * A PUT event with kv.Version=1 indicates the creation of a key.
     * A DELETE/EXPIRE event contains the deleted key with
     * its modification revision set to the revision of deletion.
     * @param ?\Mvccpb\KeyValue $prevKv prev_kv holds the key-value pair before the event happens.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Mvccpb\Event\EventType::class))]
        public \Mvccpb\Event\EventType $type = \Mvccpb\Event\EventType::PUT,
        #[Reflection\Field(2, new Reflection\ObjectT(\Mvccpb\KeyValue::class))]
        public ?\Mvccpb\KeyValue $kv = null,
        #[Reflection\Field(3, new Reflection\ObjectT(\Mvccpb\KeyValue::class))]
        public ?\Mvccpb\KeyValue $prevKv = null,
    ) {}
}
