<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/mvccpb/kv.proto
 */

declare(strict_types=1);

namespace Mvccpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KeyValue
{
    /**
     * @param string $key key is the key in bytes. An empty key is not allowed.
     * @param \BcMath\Number $createRevision create_revision is the revision of last creation on this key.
     * @param \BcMath\Number $modRevision mod_revision is the revision of last modification on this key.
     * @param \BcMath\Number $version version is the version of the key. A deletion resets
     * the version to zero and any modification of the key
     * increases its version.
     * @param string $value value is the value held by the key, in bytes.
     * @param \BcMath\Number $lease lease is the ID of the lease that attached to key.
     * When the attached lease expires, the key will be deleted.
     * If lease is 0, then no lease is attached to the key.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $key = '',
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public \BcMath\Number $createRevision = new \BcMath\Number(0),
        #[Reflection\Field(3, Reflection\Int64T::T)]
        public \BcMath\Number $modRevision = new \BcMath\Number(0),
        #[Reflection\Field(4, Reflection\Int64T::T)]
        public \BcMath\Number $version = new \BcMath\Number(0),
        #[Reflection\Field(5, Reflection\BytesT::T)]
        public string $value = '',
        #[Reflection\Field(6, Reflection\Int64T::T)]
        public \BcMath\Number $lease = new \BcMath\Number(0),
    ) {}
}
