<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/mvccpb/kv.proto
 */

declare(strict_types=1);

namespace Mvccpb\Event;

/**
 * @api
 */
enum EventType: int
{
    case PUT = 0;
    case DELETE = 1;
}
