<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\WatchCreateRequest;

/**
 * @api
 */
enum FilterType: int
{
    /** filter out put event. */
    case NOPUT = 0;

    /** filter out delete event. */
    case NODELETE = 1;
}
