<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/authpb/auth.proto
 */

declare(strict_types=1);

namespace Authpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Permission is a single entity
 */
final readonly class Permission
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Authpb\Permission\Type::class))]
        public \Authpb\Permission\Type $permType = \Authpb\Permission\Type::READ,
        #[Reflection\Field(2, Reflection\BytesT::T)]
        public string $key = '',
        #[Reflection\Field(3, Reflection\BytesT::T)]
        public string $rangeEnd = '',
    ) {}
}
