<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/authpb/auth.proto
 */

declare(strict_types=1);

namespace Authpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Role is a single entry in the bucket authRoles
 */
final readonly class Role
{
    /**
     * @param list<\Authpb\Permission> $keyPermission
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $name = '',
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Authpb\Permission::class)))]
        public array $keyPermission = [],
    ) {}
}
