<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/authpb/auth.proto
 */

declare(strict_types=1);

namespace Authpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * User is a single entry in the bucket authUsers
 */
final readonly class User
{
    /**
     * @param list<string> $roles
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BytesT::T)]
        public string $name = '',
        #[Reflection\Field(2, Reflection\BytesT::T)]
        public string $password = '',
        #[Reflection\Field(3, new Reflection\ListT(Reflection\StringT::T))]
        public array $roles = [],
        #[Reflection\Field(4, new Reflection\ObjectT(\Authpb\UserAddOptions::class))]
        public ?\Authpb\UserAddOptions $options = null,
    ) {}
}
