<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: etcd/api/authpb/auth.proto
 */

declare(strict_types=1);

namespace Authpb;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class UserAddOptions
{
    public function __construct(
        #[Reflection\Field(1, Reflection\BoolT::T)]
        public bool $noPassword = false,
    ) {}
}
