<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/authpb/auth.proto
 */

declare(strict_types=1);

namespace Authpb\Permission;

/**
 * @api
 */
enum Type: int
{
    case READ = 0;
    case WRITE = 1;
    case READWRITE = 2;
}
