<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\RequestOp;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class RequestRequestTxn implements \Etcdserverpb\RequestOp\Request
{
    public function __construct(
        #[Reflection\Field(4, new Reflection\ObjectT(\Etcdserverpb\TxnRequest::class))]
        public ?\Etcdserverpb\TxnRequest $requestTxn = null,
    ) {}
}
