<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\Compare;

/**
 * @api
 */
enum CompareTarget: int
{
    case VERSION = 0;
    case CREATE = 1;
    case MOD = 2;
    case VALUE = 3;
    case LEASE = 4;
}
