<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\Compare;

/**
 * @api
 */
enum CompareResult: int
{
    case EQUAL = 0;
    case GREATER = 1;
    case LESS = 2;
    case NOT_EQUAL = 3;
}
