<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\Compare;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TargetUnionLease implements \Etcdserverpb\Compare\TargetUnion
{
    /**
     * @param \BcMath\Number $lease lease is the lease id of the given key.
     *
     * leave room for more target_union field tags, jump to 64
     */
    public function __construct(
        #[Reflection\Field(8, Reflection\Int64T::T)]
        public \BcMath\Number $lease = new \BcMath\Number(0),
    ) {}
}
