<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\Compare;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TargetUnionCreateRevision implements \Etcdserverpb\Compare\TargetUnion
{
    /**
     * @param \BcMath\Number $createRevision create_revision is the creation revision of the given key
     */
    public function __construct(
        #[Reflection\Field(5, Reflection\Int64T::T)]
        public \BcMath\Number $createRevision = new \BcMath\Number(0),
    ) {}
}
