<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\Compare;

/**
 * @api
 * @phpstan-sealed (
 *   TargetUnionVersion |
 *   TargetUnionCreateRevision |
 *   TargetUnionModRevision |
 *   TargetUnionValue |
 *   TargetUnionLease
 * )
 */
interface TargetUnion {}
