<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\Compare;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TargetUnionModRevision implements \Etcdserverpb\Compare\TargetUnion
{
    /**
     * @param \BcMath\Number $modRevision mod_revision is the last modified revision of the given key.
     */
    public function __construct(
        #[Reflection\Field(6, Reflection\Int64T::T)]
        public \BcMath\Number $modRevision = new \BcMath\Number(0),
    ) {}
}
