<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\Compare;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TargetUnionCreateRevision implements \Etcdserverpb\Compare\TargetUnion
{
    /**
     * @param int $createRevision create_revision is the creation revision of the given key
     */
    public function __construct(
        #[Reflection\Field(5, Reflection\Int64T::T)]
        public int $createRevision = 0,
    ) {}
}
