<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\Compare;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TargetUnionValue implements \Etcdserverpb\Compare\TargetUnion
{
    /**
     * @param string $value value is the value of the given key, in bytes.
     */
    public function __construct(
        #[Reflection\Field(7, Reflection\BytesT::T)]
        public string $value = '',
    ) {}
}
