<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\DowngradeRequest;

/**
 * @api
 */
enum DowngradeAction: int
{
    case VALIDATE = 0;
    case ENABLE = 1;
    case CANCEL = 2;
}
