<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\ResponseOp;

/**
 * @api
 * @phpstan-sealed (
 *   ResponseResponseRange |
 *   ResponseResponsePut |
 *   ResponseResponseDeleteRange |
 *   ResponseResponseTxn
 * )
 */
interface Response {}
