<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\ResponseOp;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class ResponseResponseRange implements \Etcdserverpb\ResponseOp\Response
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Etcdserverpb\RangeResponse::class))]
        public ?\Etcdserverpb\RangeResponse $responseRange = null,
    ) {}
}
