<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: etcd/api/etcdserverpb/rpc.proto
 */

declare(strict_types=1);

namespace Etcdserverpb\WatchRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class RequestUnionProgressRequest implements \Etcdserverpb\WatchRequest\RequestUnion
{
    public function __construct(
        #[Reflection\Field(3, new Reflection\ObjectT(\Etcdserverpb\WatchProgressRequest::class))]
        public ?\Etcdserverpb\WatchProgressRequest $progressRequest = null,
    ) {}
}
